#controller_joint_names: ['', 'chassis_joint', 'front_left_wheel_joint', 'rear_left_wheel_joint', 'front_right_wheel_joint', 'rear_right_wheel_joint', 'laser_joint_right', 'laser_joint_left']
controller_joint_names: ['', 'chassis_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint', 'laser_joint_right', 'laser_joint_left']
