controller_manager:
  ros__parameters:
    update_rate: 50
    diff_cont:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel_names: ["rear_left_wheel_joint"]
      right_wheel_names: ["rear_right_wheel_joint"]
      publish_rate: 50
      velocity_rolling_window_size: 2
      cmd_vel_timeout: 0.5
      use_stamped_vel: false
      base_frame_id: "base_footprint"
      odom_frame_id: "odom"
      enable_odom_tf: true
      publish_cmd: true
      open_loop: true
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      left_wheel_names_multiplier: 1.0
      right_wheel_names_multiplier: 1.0
      cmd_vel_topic: "/cmd_vel_nav"
      # Add these deadband parameters
      velocity_threshold: 0.001          # Ignore velocities smaller than this
      min_x_velocity_threshold: 0.001    # Minimum linear velocity to consider
      min_theta_velocity_threshold: 0.001 # Minimum angular velocity to consider
      # Add these parameters
      wheel_separation: 0.50        # Distance between your wheels (2 * 0.25 from your URDF)
      wheel_radius: 0.10            # Matches your URDF
      wheel_separation_multiplier: 1.0  # Add this - fine tune if needed
      left_wheel_radius_multiplier: 1.0 # Add this
      right_wheel_radius_multiplier: 1.0 # Add this
      # Velocity limits
      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.max_velocity: 0.5
      linear.x.min_velocity: -0.5    # Enable backward motion
      linear.x.max_acceleration: 1.0
      linear.x.min_acceleration: 1.0
      # Add these to potentially dampen feedback
      position_feedback: false
      use_stamped_vel: false
      # Angular limits
      angular.z.has_velocity_limits: true
      angular.z.has_acceleration_limits: true
      angular.z.max_velocity: 1.0
      angular.z.min_velocity: -1.0
      angular.z.max_acceleration: 1.0
      angular.z.min_acceleration: -1.0
      cmd_vel_timeout: 0.5
      publish_limited_velocity: true
      velocity_rolling_window_size: 1

    joint_broad:
      type: "joint_state_broadcaster/JointStateBroadcaster"