controller_manager:
  ros__parameters:
    update_rate: 50
    diff_cont:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel_names: ["rear_left_wheel_joint"]
      right_wheel_names: ["rear_right_wheel_joint"]
      publish_rate: 50
      velocity_rolling_window_size: 2
      cmd_vel_timeout: 0.5
      use_stamped_vel: false
      base_frame_id: "base_footprint"
      odom_frame_id: "odom"
      enable_odom_tf: true
      publish_cmd: true
      open_loop: true
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    joint_broad:
      type: "joint_state_broadcaster/JointStateBroadcaster"