controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Add these lines to declare your controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

# Add this section for the hardware interface
hardware_interface:
  ros__parameters:
    use_sim_time: true
    robot_description: $(arg robot_description)

    joint_names:
      - rear_left_wheel_joint
      - rear_right_wheel_joint

    loop_hz: 50
    use_fake_hardware: false

    robot_name: augv
    control_mode: velocity

    gazebo:
      use_sim_time: true
      use_clock_topic: /clock

# Your existing diff_drive_controller configuration
joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint"]
    wheel_separation: 0.4191
    wheel_radius: 0.1016
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    use_stamped_vel: false

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 0.5
        min_acceleration: -0.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5
        min_velocity: -1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0