controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint"]
    publish_rate: 50
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    wheel_separation: 0.26
    wheel_radius: 0.075
